ministryofjustice/serve-opg

- docker-compose.yml
Removing a revoked Notify API key prior to the project being made open source.
Closes DDPB-3222.
> Remove notify key

- .circleci/config.yml
- docker/app/Dockerfile
Added dockerhub creds to circle. Also locked composer because of last nights update.
DDPB-3745
> DDPB-3745 add dockerhub creds to circle

- yarn.lock
update serious security flaw flagged by dependabot
[List any existing issues this PR resolves]
> DDPB-3773 update security

- .circleci/config.yml
- config/services.yaml
- docker-compose.test.yml
- docker-compose.yml
- features/00-security.feature
- features/03-login.feature
- features/04-cases.feature
- features/05-deputy.feature
- features/05-documents.feature
- features/06-serve.feature
- features/07-password-reset.feature
- features/08-report.feature
- features/09-user-management.feature
- src/Behat/FeatureContext.php
- src/Controller/BehatController.php
- src/DataFixtures/adminUsers.yaml
- src/DataFixtures/testUsers.yaml
- src/TestHelpers/FixtureTestHelper.php
- src/TestHelpers/UserTestHelper.php
- tests/ApiWebTestCase.php
- tests/Controller/UserControllerTest.php
- tests/Entity/UserTest.php
Make all the behat passwords use variables instead of being hardcoded so that we can change their values through secrets in dev and preprod.
[List any existing issues this PR resolves]
> Ddpb 3773b

- README.md
- docs/pull_request_template.md
- docs/runbooks/DEBUGGING.md
- docs/runbooks/PULL-REQUEST-AND-RELEASE-PROCEDURE.md
- docs/runbooks/TESTING.md
Adding some runbooks to the project to document/split up some new and existing guidance.
DDPB-3823
> DDPB-3823: Update runbooks

- .circleci/config.yml
> Fix filepath for docker_login.sh

- serve-web/composer.json
- serve-web/composer.lock
Bumping symfony/flex to ensure the app will still work when the flex serve goes away in the near future.
Fixes SER-89
> Bump symfony/flex

- serve-web/composer.json
- serve-web/composer.lock
Removes an out of date dependency
> Update PHP Unit 

- .github/workflows/build.yaml
- Makefile
- serve-web/features/05-deputy.feature
Also fixed a local issue where localstack doesn't create dynamodb resources due to using old localstack ports.
> Fix incorrect assertion when editing deputy

- docker-compose.yml
> Update to postgres 10 image

- .github/workflows/dependabot.yml
Use "-" separator in branch names to make container tagging work
> Fix dependabot

- serve-web/templates/User/view-users.html.twig
Adding date contexts for users so we can support information security requests.
SER-111
> SER-111: Add user dates

- .github/workflows/build.yaml
Updating references of `master` to `main` in GA steps. I've already changed the default branch to `main` in GitHub.
> Change local repo refs of master to main

- README.md
- serve-web/composer.lock
Rename dependabot branch to use - not /
> Dependabot composer serve web twig twig 3.3.8

- .github/workflows/dependabot.yml
> Add composer to dependabot file with - separator

- serve-web/docker/app/Dockerfile
> Add busybox to force upgraded packages.

- serve-web/docker/app/Dockerfile
Update curl gzip xz xz-libs libcurl packages
> Update alpine packages

- docker-compose.override.yml
DDPB-XXXX [List any existing issues this PR resolves]
> [SER-166] added air command

- README.md
replaces the CircleCI badge with the Github Actions one
> replace circleci badge with gh actions

- serve-web/api.public.v1.yaml
- serve-web/src/Service/SiriusService.php
- serve-web/tests/Service/SiriusServiceTest.php
Fix to the logout function so it doesn't break
> DDPB-4472 update the logout function

- .github/workflows/containers.yml
- .github/workflows/web.yml
- serve-web/package.json
- serve-web/yarn.lock
> Try encore update to 2.0

- terraform/terraform.tfvars.json
> SER-181 - update prod rds instance class before version update

- terraform/terraform.tfvars.json
> SER-181 - re-apply rds prod version

- .github/workflows/behat.yml
- .github/workflows/web.yml
> SER-171 - add php package caching to behat job

- terraform/alarms.tf
> SER-191 - append envrionment name to alarm names

- serve-web/composer.lock
> Update security related packages

- terraform/notifications.tf
> Move US-east alert to serve channel

- README.md
- serve-web/docker/app/Dockerfile
- serve-web/docker/app/serve-opg.ini
Friday test of 8.1 upgrade path feasibility.
> Test PHP 8.1

- serve-web/src/Controller/ReportController.php
- serve-web/src/DataFixtures/adminUsers.yaml
- serve-web/src/Repository/OrderRepository.php
- serve-web/src/Service/ReportService.php
- serve-web/templates/Report/report.html.twig
- serve-web/tests/Service/ReportServiceTest.php
SER-208 [List any existing issues this PR resolves]
> SER-208: Download reports of orders served and not served

- .github/workflows/behat.yml
- .github/workflows/containers.yml
- .github/workflows/deploy.yml
- terraform/s3.tf
Update GH action dependencies to address deprecation warnings in the pipeline
> SER-186 - update action dependencies

- terraform/rds.tf
Final change as part of 4845 to remove the old database.
> DDPB-4845c remove the old provisioned DBs

- terraform/secrets.tf
Adds secret for new Cloud99 setup
> DDLS-134 - add c9 user secret

- .github/workflows/deploy.yml
- terraform/.terraform.lock.hcl
- terraform/versions.tf
> Updating terraform to 1.7.3

- terraform/config_file.tf
- terraform/ecs_service_front.tf
- terraform/load_balancer.tf
- terraform/moved.tf
- terraform/rds.tf
> SER-226 pre work to change resource names

- terraform/environment/esc_task_front.tf
Move to the correct environment based roles and log groups now that they have been created on sirius side.
SER-227 [List any existing issues this PR resolves]
> SER-227b switch to the new environment based roles

- terraform/account/dynamodb.tf
- terraform/account/iam.tf
- terraform/account/secrets.tf
- terraform/account/vpc.tf
- terraform/environment/cloudwatch_dashboard.tf
- terraform/environment/ecs_iam.tf
- terraform/environment/ecs_service_front.tf
- terraform/environment/esc_task_front.tf
- terraform/environment/rds.tf
- terraform/environment/s3.tf
- terraform/environment/secrets.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
- terraform/environment/waf.tf
Clean up our folders. This PR is in conjunction with some state moves. Makes it easier to do the shift over to PR environments.
SER-165 [List any existing issues this PR resolves]
> SER-165 pre work to make project fit for branch envs

- .github/workflows/workflow-destroy-on-merge.yml
- scripts/cleanup/destroy_workspace.sh
- scripts/cleanup/workspace_cleanup.sh
- terraform/environment/s3.tf
Fix cleanup job
SER-165 [List any existing issues this PR resolves]
> SER-165d fix cleanup job

- .github/workflows/workflow-destroy-on-merge.yml
- serve-web/src/DataFixtures/adminUsers.yaml
Shouldn't have this as fixture data
SER-224 [List any existing issues this PR resolves]
> SER-224 amend fixture admin users

- serve-web/docker/web/Dockerfile
- serve-web/docker/web/etc/confd/templates/default.conf.tmpl
- serve-web/docker/web/nginx.conf
- terraform/environment/rds.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Better nginx logging
Currently the logging is hard to search and create cloudwatch insight queries against. By using json formatted logs, we can easily search individual fields and alarms become easier to create as well.. 
I also scaled down the rds cluster for dev envs to save some dollar..
SER-222 [List any existing issues this PR resolves]
> SER-222 better json logging

- .github/workflows/workflow-live-path.yml
- serve-web/.env
- serve-web/.env.test
- serve-web/config/packages/doctrine.yaml
- serve-web/docker/app/Dockerfile
- serve-web/src/TestHelpers/OrderTestHelper.php
- terraform/environment/esc_task_front.tf
- terraform/environment/rds.tf
Add the RDS certs for SSL and use SSL
Checked the plan on preprod and prod and it only modifies the DB instance.
Additionally I have removed the development environment from our path to live as we don't need it any more.
SER-183 [List any existing issues this PR resolves]
> DDLS-183 fix the RDS certs

- .github/workflows/workflow-live-path.yml
- .github/workflows/workflow-pull-request-path.yml
- README.md
Update the readme. Make it much shorter and simpler to read.
SER-220 [List any existing issues this PR resolves]
> SER-220 update and simplify readme

- terraform/environment/load_balancer.tf
Hitting limits on number sec group rule size. Split the HC rules into own SG and add it to the LB config.
SER-231 [List any existing issues this PR resolves]
> SER-231 allow list the hc properly

- serve-web/src/Service/Availability/NotifyAvailability.php
- serve-web/src/Service/Availability/SiriusApiAvailability.php
Fix the endpoint as it was coming up with 5xx errors
SER-233 [List any existing issues this PR resolves]
> SER-233 fix dependency endpoint

- .github/workflows/_build-push.yml
Process was not tagging main properly!
SER-235 [List any existing issues this PR resolves]
> SER-235 fix the ecr image tagging

- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/_tests-behat.yml
- serve-web/docker/app/Dockerfile
- serve-web/docker/web/Dockerfile
> DDLS-332 update the php container

- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/_tests-behat.yml
New version of upload config expects different named artefacts
SER-332 [List any existing issues this PR resolves]
> DDLS-332b fix upload config

- serve-web/docker/app/Dockerfile
- serve-web/docker/waitforit/Dockerfile
- serve-web/docker/web/Dockerfile
- terraform/environment/rds.tf
> DDLS-435 change rds scaling to min 0

- terraform/account/cloudwatch_queries.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
Add cloudwatch insight queries to assist developers in diagnosing live issues. 
DDLS-475 [List any existing issues this PR resolves]
> DDLS-475 add cloudwatch insights queries

- .github/workflows/_build-push.yml
- .github/workflows/_deploy-infrastructure.yml
- .github/workflows/_tests-behat.yml
- .github/workflows/_tests-frontend.yml
- .github/workflows/scheduled-workspace-cleanup.yml
- .github/workflows/workflow-destroy-on-merge.yml
- .github/workflows/workflow-live-path.yml
- .github/workflows/workflow-pull-request-path.yml
- renovate.json
pin all to shas and add reonvate helper so it only updates to tagged versions.
SER-524 [List any existing issues this PR resolves]
> DDLS-526 pin all actions to shas with tag in comments

- README.md
> added docker desktop settings to README

- .github/workflows/_build-push.yml
- docker-compose.yml
- serve-web/docker/waitforit/wait-for-it.sh
- serve-web/docker/web/Dockerfile
- serve-web/docker/web/default.conf.tmpl
- serve-web/docker/web/etc/confd/conf.d/nginx.toml
- terraform/environment/esc_task_front.tf
Removing confd and waitforit because they are not needed and confd is not supported by an active team of devs
DDLS-575 [List any existing issues this PR resolves]
> DDLS-575 removed confd from nginx

- serve-web/docker/app/Dockerfile
- serve-web/docker/waitforit/Dockerfile
Just like DDLS-575 but this time it had no nginx, so it was just the wait for it to be turned into a shell script. i also removed the waitforit dockerfile as its no longer in use.
> Replaced wait-for-it in app to be a shell script.

- serve-web/src/Service/ReportService.php
> DDLS-574: Add DateIssued and DateMade to all served orders report

- .github/workflows/_build-push.yml
> add trivy to serve

- terraform/environment/terraform.tfvars.json
> DDLS-680 update latest version of 13 aurora

- serve-web/composer.lock
> DDLS-854 update composer

- scripts/cycle_secrets/cycle_secrets.py
- terraform/account/modules/ssm_ec2_instance/boot.sh
> fix to rotation script

- .github/workflows/_notify-slack.yml
- scripts/slack_notify/slack_notify.py
> Fixed script and updates payload to make a JSON file first then send it
