docker-compose.yml
src/Entity/Deputy.php
src/Entity/Order.php
src/Form/DeputyForm.php
src/TestHelpers/OrderTestHelper.php
tests/Entity/DeputyTest.php
tests/Form/DeputyFormTest.php
translations/validators.en.yml

As a OPG user
I want the COP users to enter the deputy DOB and I want the COP users to enter the deputy address
So that the deputy can be matched when the order is served and duplicates are not created in Sirius

DDPB-3705: Make date of birth and address fields mandatory

---

.circleci/config.yml

To have a minimal level of confidence in the integration with Sirius we should be running our integration tests at least daily. This change adds a cron job to do just that at 2AM each morning.
I've also taken the opportunity to break the circleci test steps up into some chunks to make re-use a little easier in the future. 
DDPB-3433

DDPB-3433: Add step to pipeline to run tests at 2AM daily

---

config/services.yaml
src/Controller/PostcodeController.php
src/Service/AddressLookup/OrdnanceSurvey.php
tests/Service/OrdnanceSurveyServiceTest.php

Postcode lookup had missing configuration which led to all requests being sent out failing.
Has been fixed by giving the OrdnanceSurvey service it's own GuzzleClient config with required arguments.
Also fixed an issue with the logging of errors for the postcode lookup.
DDPB-3820

DDPB-3820 - Fix postcode lookup for Serve OPG

---

docker/app/Dockerfile
docker/notify/Dockerfile

Locking for now to avoid postgres driver issues on 7.4.18 - https://bugs.php.net/bug.php?id=81002

Lock PHP to 7.4.16

---

serve-web/src/Controller/OrderController.php
serve-web/templates/Case/index.html.twig
serve-web/templates/Order/summary-served.html.twig

Adds basic template for served order summary pages. Some functionality on the prototype doesn't exist yet so this feature will be revisited once its implemented.

SER-81: Add endpoint for served order summary and link from served tab

---

.circleci/config.yml
.env
Makefile
docker-compose.yml
serve-web/.env
serve-web/README.md
serve-web/src/Service/S3Client.php

The version of localstack we were using included an old version of pip based on python 2.7 which is unsupported and blocking our release pipeline in serve-opg-infrastructure. This bumps the version up to ensure we're using a supported version of python (3.8).
There were some changes to the default behaviour of localstack during the upgrade:
- Bucket names no longer allow underscores
- By default, bucket names are prepended to bucket URLs
Due to these changes I've updated the bucket name and set the default bucket URL to be path based rather than domain/bucket name-based.

Bump localstack

---

serve-web/features/05-deputy.feature
serve-web/src/Controller/DeputyController.php
serve-web/src/Form/DeputyForm.php
serve-web/templates/Deputy/add.html.twig
serve-web/templates/Deputy/type.html.twig
serve-web/templates/Order/summary.html.twig
serve-web/tests/Form/DeputyFormTest.php
serve-web/translations/forms.en.yml

This was a little more involved than expected as the deputy type is defined on the same page that we request DOB. Rather than rely on JS I've broken the deputy type question out to a new page that appears before the deputy details screen so we have that value ready to alter the fields in the form before its rendered:

SER-28: Stop requesting DOB for PA/Prof deputies

---

.circleci/config.yml

Seeing some weirdness in [CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/serve-opg/2025/workflows/123a7948-f71c-41d5-baa9-5abbddc7e23b/jobs/2366) when trying to run `docker/install-docker-credential-helper` so seeing if an up to date version does the trick.

Bump circleci/docker orb

---

.circleci/config.yml
docker-compose.yml

- Use a smaller and more up to date Docker container for node.
- Pin Prism to fix mocks
- Update test and artefact locations

Switch to node 16 alpine

---

.github/workflows/build.yaml

As infra pipeline relies on there being a `latest` tag we need to make sure we push the semvar and latest tag together.

Push all tags when branch is master

---

serve-web/features/00-init.feature
serve-web/src/Controller/BehatController.php

In preprod the test database contains data from the development test run. This wasn't an issue prior to load testing 2499 row CSV uploads but now this breaks existing tests due to items being expected on the page. This ensures we start with a fresh database at the start of each test run.
Longer-term we want tests to be in isolation so this is a stop-gap measure for now.

Reset behat fixtures inside tests

---

serve-web/yarn.lock

Recreate the dependabot branch without slashes.

Bump follow-redirects from 1.14.1 to 1.14.7 in /serve-web

---

serve-api/entity/client.go
serve-api/entity/deputy.go
serve-api/entity/document.go
serve-api/entity/order.go
serve-api/entity/user.go
serve-api/internal/cache/cache.go
serve-api/internal/db/db.go
serve-api/internal/session/session.go

All exported functions/structs in Go should be commented with what they are trying to achieve. This allows the use of the `go doc` comment which will extract all exported functions into a documentation type web page with the comments explaining what each one is doing

modified: added comments to exported functions to follow Go's effective Go handbook

---

serve-api/main.go

Failing to cancel the context that WithTimeout() returns means the
goroutine created will be retained in memory indefinitley which causes
memory leaks
More learnings here: https://go.dev/src/context/context.go?s=9162:9288
>// The WithCancel, WithDeadline, and WithTimeout functions take a
// Context (the parent) and return a derived Context (the child) and a
// CancelFunc. Calling the CancelFunc cancels the child and its
// children, removes the parent's reference to the child, and stops
// any associated timers. Failing to call the CancelFunc leaks the
// child and its children until the parent is canceled or the timer
// fires. The go vet tool checks that CancelFuncs are used on all
// control-flow paths.

added: the call to the cancel() function returned from WithTimeout()

---

.github/workflows/behat.yml

Unset aws config made by configure-aws-credentials before CI ingress runs, to allow proper roles to be assumed
Intent is to refactor this once the path to live is unblocked

SER-176 - unset aws creds before allowing CI ingress

---

serve-web/api.public.v1.yaml
serve-web/src/Service/SiriusService.php
serve-web/tests/Service/SiriusServiceTest.php

Due to a change to sirius frontend login, the auth/login endpoint no longer logs us in to sirius. As such we need to change it to the old-login endpoint instead.
DDPB-4472

DDPB-4472 fix auth to sirius

---

serve-web/composer.lock

Recreated from dependabot PR.
Bumps [twig/twig](https://github.com/twigphp/Twig) from 3.4.2 to 3.4.3.
- [Release notes](https://github.com/twigphp/Twig/releases)
- [Changelog](https://github.com/twigphp/Twig/blob/3.x/CHANGELOG)
- [Commits](https://github.com/twigphp/Twig/compare/v3.4.2...v3.4.3)
---
updated-dependencies:
- dependency-name: twig/twig dependency-type: indirect ...
Signed-off-by: dependabot[bot] <support@github.com>

Bump twig/twig from 3.4.2 to 3.4.3 in /serve-web

---

terraform/rds.tf

We need to upgrade the rds instance to the newer r5 type to allow the psql13 upgrade

SER-181 - upgrade rds instance class

---

.github/workflows/deploy.yml
terraform/.terraform.lock.hcl
terraform/notifications.tf

Upgrade to latest version of aws notify slack as the old version is using deprecated AWS Terraform resources
Setting TF_WORKSPACE for the init step is necessary to upgrade a v0.12 instance to v0.13 which the latest version of aws-notify-slack uses
SER-204

SER-204 - Upgrade to latest version of aws notify slack #patch

---

terraform/notifications.tf

The upgrade of aws-notify-slack is trying to create two IAM roles with the same name.. added a prefix to the us-east-1 role to fix this

Add a prefix for us east iam role #patch

---

.github/workflows/containers.yml

Fixes builds to avoid dependabot builds failing due to not having creds to push to ECR.

Exclude dependabot PRs from trying to push containers

---

.gitignore
terraform/.terraform.lock.hcl
terraform/rds.tf
terraform/task_definition.tf

Move to serverless v2 without destroying current provisioned DB.
Next follow up ticket will destroy the current DB.
DDPB-4845

DDPB-4845 switch db to serverless v2

---

terraform/rds.tf

We don't need egress sg rule for RDS. Not sure why it's there. Removing the deletion protection to old DB in this PR so that we may delete the old DBs in next PR.
DDPB-4845b

DDPB-4845b remove deletion protection from original DB

---

serve-web/docker/app/Dockerfile
serve-web/docker/web/Dockerfile

Internal dependencies were breaking builds due to container upgrade

SER-165 upgrade the containers dependencies

---

terraform/account/cloud9.tf
terraform/account/secrets.tf
terraform/environment/terraform.tfvars.json

We had to remove the c9 from tfstate as part of the move to environments. This PR in conjunction with some background tf state moves readds it back in.
SER-229 [List any existing issues this PR resolves]

SER-229 readd c9 to tfstate

---

terraform/environment/cloudwatch_dashboard.tf

Added the uptime to the serve dashboard and jsonencoded the dash.
Haven't formatted the dash (which needs an overhaul) as part of this ticket.
SER-232 [List any existing issues this PR resolves]

SER-232 add uptime to the dashboard

---

terraform/environment/.terraform.lock.hcl
terraform/environment/terraform.tfvars.json
terraform/environment/versions.tf

Update non prod rds v2 min scaling to 0 - Part 1
Upgrade rds before it allows auto pause.
Upgrade AWS version to allow the scaling change
SER-435 [List any existing issues this PR resolves]

DDLS-435 Update non prod rds v2 min scaling to 0

---

docker-compose.test.yml
serve-web/phpunit.xml.dist
serve-web/src/Service/CsvImporterService.php
serve-web/src/Service/OrderService.php
serve-web/src/Service/SpreadsheetImporterService.php
serve-web/tests/Service/CsvImporterServiceTest.php
serve-web/tests/Service/SpreadsheetImporterServiceTest.php
serve-web/tests/TestData/cases.csv

Change the logic so that if a order number doesn't already exist, it will create a new row for that order even if it has the same client. 
So if we have client abcd with order 1234 and we add a row with client abcd and order 5678 then it will create both rows.
However, I had issues with where it was doing the flush that meant it was working weirdly in different ways. I've put the flush after every row. This will be slower but it does mean it won't bug out and miss rows!
SER-458 [List any existing issues this PR resolves]

DDLS-458 fix csv importer

---

serve-web/src/Controller/CaseController.php
serve-web/src/Repository/OrderRepository.php
serve-web/src/Service/ReportService.php
serve-web/tests/Service/ReportServiceTest.php

Apply fix to prevent the 'All Served Orders' report from timing out due to the large data set fetched when generating the CSV
The fix was to fetch the data as an associative array instead of objects for this specific report.

DDLS-519: Rewrite serve download report so it doesn't time out
